blank_issues_enabled: false
contact_links:
  - name: Flutter Community Support
    url: https://stackoverflow.com/search?q=flutter
    about: Please ask and answer questions here.
  - name: New to Flutter?
    url: https://gitter.im/flutter/flutter
    about: Chat with other Flutter developers on Gitter.
